export { default as Navbar } from './NavbarUp/Navbar'
export { default as Main } from './Main/Main'
export { default as Sidebar } from './Sidebar/Sidebar'
export { default as Profile } from './Profile/Profile'
export { default as Repartition } from './Repartition/Repartition'
export { default as CreateRepartition } from './Criar/CreateRepartition'
export { default as GerenciarUsuarios } from './GerenciarUsuarios/GerenciarUsuarios'